os:
  - linux
  - osx

language: cpp

dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7


before_install:
  - pip install --user cpp-coveralls

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    export CC=gcc-7 ;
    export CXX=g++-7 ;
    fi
  - cmake -DCOVERAGE=1 .
  - cmake --build .
  - ./sherpa_41-test


after_success:
  - coveralls --root . -e tests -e lib -E ".*CMakeFiles.*"